### ISSUE TITLE
Email is come before 24 hours

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/post-purchase-experience#8]
Here i placed the order on 20 June at 4:30 PM and when i see customer email account then i got an email from Word Press.

I have placed two order
http://staging.tychesoftwares.com/woo_apeksha/checkout/order-received/5829/?key=wc_order_5947adc3b7016 (This order is for date and time slot that is 19 June 7:00 Pm to 8 PM)

http://staging.tychesoftwares.com/woo_apeksha/checkout/order-received/5830/?key=wc_order_5947ae8cb5b08 (This order placed with date that is 19 June ) 

As per plugin works customer received email at 20 June at 4:30 Pm (this is for 1 order) and for second order customer received email at 20 June 7:00PM

Screenshot of customer email #5830  https://www.screencast.com/t/sPRr23zDf
Screenshot of Customer emil #5829 https://www.screencast.com/t/GyPIx9arWfk

**Comment by ashokrane** [comment]
Closing this issue as no other client has reported it & it's an old issue.
