### ISSUE TITLE
Did not receive the emails from the plugin even after a day of delivery.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/post-purchase-experience#9]
Did not receive the emails from the plugin even after a day of delivery of an order. Tried by running the cron manually as well but no post-purchase emails.

Today is 27 Nov, 2018: https://prnt.sc/lni9ui . Orders: https://prnt.sc/lni9l0

Core plugin:9.0.1
Addon: 1.0

System status of core plugin:
### WordPress Environment ###

Home URL: http://localhost/wp_beta 
Site URL: http://localhost/wp_beta 
WP Version: 5.0-RC1-43944 
WP multisite: No 
WP debug mode: On 
WP Language: en-US 
WC Version: 3.5.1 

### Plugin Settings ###

Plugin Version: 9.0.1 
License Key: e3ebb6f346eaa693aecf6a31aa10d405 
License Status: valid 
Enable Delivery Date: on 
Delivery Checkout options: delivery_calendar 
Delivery Days: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday 
Enable Weekday Settings:  
Minimum Delivery time (in hours): 0 
Number of dates to choose: 30 
Delivery Date Field Mandatory:  
Maximum Order Deliveries per day (based on per order):  
Enable Maximum Deliveries based on per product quantity:  
Enable Shipping days based calculation:  
Shipping Days:  
Delivery Range: 1 - 3 
Enable Specific Delivery Dates:  
Specific Delivery Dates:  
Enable delivery time capture:  
Time Range: :00 - :59 
Enable Same day delivery:  
Cut-off time for same day delivery orders: : 
Additional Charges for same day delivery:  
Enable Next day delivery:  
Cut-off time for next day delivery orders: : 
Additional Charges for next day delivery:  
Holidays:  
Calendar Language: en-GB 
Date Format: d MM, yy 
Time Format: 2 
First Day of Week: Monday 
Number of Months: 1 
Calendar Theme: Smoothness 
Locations Label: Pickup Location 
Date Field Label: Delivery Date 
Time slot Field Label: Time Slot 
Field Placeholder Text: Choose a Date 
Field Note Text: We will try our best to deliver your order on the specified date. 
Fields placement on the Checkout page: billing_section 
Custom Hook for Field Placement:  
Delivery Date field on Cart page:  
Holiday Color: #ff0000 
Booked Dates Color: #ff0000 
Cut-off time over Dates Color: #ff0000 
Available Dates Color: #90EE90 
Enable time slot capture:  
Time slot Field Mandatory:  
Show 'As Soon As Possible' option:  
Global Maximum Order Deliveries for Time slots:  
Auto-populate first available delivery time slot:  
Time slots: Time Slot for: weekdays, Delivery Days/Dates: All, Time Slot: 8:00  - 9:00 , Lockout: , Additional Charges: , Additional Charges Label: <br>Time Slot for: weekdays, Delivery Days/Dates: All, Time Slot: 9:00  - 10:00 , Lockout: , Additional Charges: , Additional Charges Label: <br>Time Slot for: weekdays, Delivery Days/Dates: All, Time Slot: 10:00  - 11:00 , Lockout: , Additional Charges: , Additional Charges Label: <br>Time Slot for: weekdays, Delivery Days/Dates: All, Time Slot: 11:00  - 12:00 , Lockout: , Additional Charges: , Additional Charges Label:  
Show on Orders Listing Page: on 
Enable Default Sorting of Delivery Date field on WooCommerce Orders listing page: on 
Show Filter on Orders Listing Page: on 
Auto-populate first available Delivery date: on 
Enable Tax calculation for Delivery charges:  
Disable the Delivery Date and Time Slot Fields for Virtual Products: on 
Disable the Delivery Date and Time Slot Fields for Featured Products:  
Allow Customers to edit Delivery Date & Time: on 
WooCommerce Customer/ Order CSV Export plugin: on 
WooCommerce PDF Invoices & Packing Slips plugin: on 
WooCommerce Print Invoice & Delivery Note plugin: on 
WooCommerce Print orders plugin: on 
WooCommerce Shipping Multiple addresses:  
WooCommerce Amazon Payments Advanced Gateway:  
Send email to admin when date updated: on 
Weekday Settings:  
Sunday Additional Charges:  
Sunday Additional Charges Label:  
Monday Additional Charges:  
Monday Additional Charges Label:  
Tuesday Additional Charges:  
Tuesday Additional Charges Label:  
Wednesday Additional Charges:  
Wednesday Additional Charges Label:  
Thursday Additional Charges:  
Thursday Additional Charges Label:  
Friday Additional Charges:  
Friday Additional Charges Label:  
Saturday Additional Charges:  
Saturday Additional Charges Label:  
Custom Delivery: on 
Custom Delivery Setting 1: <b>Delivery Based on:</b> shipping_methods<br><b>Shipping Methods:</b> flat_rate:1<br><b>Enable Delivery Date:</b> on<br><b>Delivery Checkout options:</b> delivery_calendar<br><b>Delivery Type:</b> Weekdays,<br><b>Weekdays:</b> <br>Weekday: Sunday, Additional Charges: , Additional Charges Label: <br>Weekday: Monday, Additional Charges: , Additional Charges Label: <br>Weekday: Tuesday, Additional Charges: , Additional Charges Label: <br>Weekday: Wednesday, Additional Charges: , Additional Charges Label: <br>Weekday: Thursday, Additional Charges: , Additional Charges Label: <br><b<br><b>Specific Dates:</b> <br><b>Minimum delivery Time (in Hours):</b> <br><b>Number of Dates to choose:</b> 30<br><b>Maximum Order Deliveries per day:</b> <br><b>Between Range:</b> 1 - 3<br><b>Time Range:</b> 0:00 - 0:59<br><b>Same Day Cut-off:</b> 0:00, Additional Charges: <br><b>Next Day Cut-off:</b> 0:00, Additional Charges: <br><b>Time Slots:</b> <br><br><b>Holidays:</b> <br><b>Delivery Date Field Label:</b> <br><b>Delivery Time Field Label:</b>  
Event Location: ADDRESS 
Event summary (name): SITE_NAME - ORDER_NUMBER 
Event Description: CLIENT (EMAIL), <br> PRODUCT_WITH_QTY 
Show Add to Calendar button on Order received page:  
Show Add to Calendar button in the Customer notification email:  
Show Add to Calendar button on My account:  
Open Calendar in Same Window:  
Integration Mode:  
Google Calendar Sync Details:  
Show Add to Calendar button on Delivery Calendar page:  
Show Add to Calendar button in New Order email notification:  
Pickup Locations:  
Pickup Locations Mandatory?:  
Number of days for reminder before Delivery Date:  
Reminder Email Message:  
Reminder Email Subject:  
Allow Tracking: no 
Welcome Page Shown: yes 
Welcome Page Shown Time: 1543228941 
Delivery Date Availability Calendar:

**Comment by ashokrane** [comment]
Closing this issue as no client has reported it until now.
